name: '[DOMO] Deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run NextJS Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            export PATH="/home/ubuntu/.local/share/fnm:$PATH"
            eval "`fnm env`"

            alias pm2='authbind --deep pm2'

            cd /home/ubuntu/CG_sc23-Main_FE

            git pull -X theirs
            yarn clean
            yarn install --production

            pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js

      - name: Update Deployment Status (Success)
        if: success()
        uses: bobheadxi/deployments@v1.4.0
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: success
          env: Production
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update Deployment Status (Failure)
        if: failure()
        uses: bobheadxi/deployments@v1.4.0
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: failure
          env: Production
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
